/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Objects.Account;
import Objects.FileHandling;
import Objects.TransactionLog;
import java.awt.Color;
import java.text.DecimalFormat;
/**
 *
 * @author philip
 */
public class BalanceInquiry extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    private Account account;
    private TransactionLog log;
    
    public BalanceInquiry(Account account){
        this.account = account;
   
        log = new TransactionLog(account.getAccountNumber(), "Balance Inquiry", 0);
        initComponents();
    }
    
    
    private void generateReceipt(){
        FileHandling filehandler = new FileHandling();
        filehandler.saveLog(log.getLog());
        filehandler.saveReceipt(account.getAccountNumber(), "Balance Inquiry", 0);
    }
    
    public BalanceInquiry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        errorMessage1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumber = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        errorMessage2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updatedBalance1 = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        errorMessage3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        issuedDate = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel8 = new javax.swing.JLabel();
        backToTransactionButton1 = new UI_Components.BackButton(null,"Back to Transaction Menu");
 ;
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receipt");
        setBackground(new java.awt.Color(231, 230, 221));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(231, 230, 221));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(3404, 561));
        jPanel1.setLayout(new java.awt.GridLayout(9, 3, 0, 25));
        jPanel1.add(jLabel19);
        jPanel1.add(jLabel17);
        jPanel1.add(jLabel21);
        jPanel1.add(jLabel22);

        errorMessage.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(232, 199, 102));
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setText("Balance Inquiry");
        errorMessage.setText("");
        jPanel1.add(errorMessage);
        jPanel1.add(jLabel15);
        jPanel1.add(jLabel18);
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel16);

        errorMessage1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        errorMessage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage1.setText("Account Number:");
        errorMessage.setText("");
        jPanel1.add(errorMessage1);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);

        accountNumber.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        accountNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumber.setText("19216191");
        accountNumber.setText(account.getAccountNumber());
        accountNumber.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                accountNumberAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(accountNumber);

        errorMessage2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        errorMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage2.setText("Balance:");
        errorMessage.setText("");
        jPanel1.add(errorMessage2);
        jPanel1.add(jLabel6);

        updatedBalance1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        updatedBalance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatedBalance1.setText("69420");

        updatedBalance1.setText("₱ " + String.valueOf(Math.floor(account.getAccountBalance() * 100) / 100));
        updatedBalance1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                updatedBalance1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(updatedBalance1);

        errorMessage3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        errorMessage3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage3.setText("Issued Date:");
        errorMessage.setText("");
        jPanel1.add(errorMessage3);
        jPanel1.add(jLabel7);

        issuedDate.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        issuedDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issuedDate.setText("6/08/2022");

        issuedDate.setText(log.getDateTime());
        issuedDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                issuedDateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(issuedDate);
        jPanel1.add(jLabel8);

        backToTransactionButton1.setBackground(new java.awt.Color(51, 97, 172));
        backToTransactionButton1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        backToTransactionButton1.setForeground(java.awt.Color.white);
        backToTransactionButton1.setText("Back to Transaction Menu");
        backToTransactionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToTransactionButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backToTransactionButton1);
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel10);
        jPanel1.add(jLabel11);
        jPanel1.add(jLabel12);
        jPanel1.add(jLabel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuedDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_issuedDateAncestorAdded

    }//GEN-LAST:event_issuedDateAncestorAdded

    private void accountNumberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_accountNumberAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberAncestorAdded

    private void updatedBalance1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_updatedBalance1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_updatedBalance1AncestorAdded

    private void backToTransactionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToTransactionButton1ActionPerformed
        Transaction transaction = new Transaction(account);
        transaction.setVisible(true);
        transaction.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_backToTransactionButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceInquiry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceInquiry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JButton backToTransactionButton1;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel errorMessage1;
    private javax.swing.JLabel errorMessage2;
    private javax.swing.JLabel errorMessage3;
    private javax.swing.JLabel issuedDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updatedBalance1;
    // End of variables declaration//GEN-END:variables
}
