/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Objects.Account;
import Objects.FileHandling;
import Objects.TransactionLog;
import java.awt.Color;
import java.text.DecimalFormat;
/**
 *
 * @author philip
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    private Account account;
    private String operationTypeValue, issuedAmountValue;
    private TransactionLog log;
    
    public Receipt(Account account, String operationTypeValue, String issuedAmountValue){
        this.account = account;
        this.operationTypeValue = operationTypeValue;
        this.issuedAmountValue = issuedAmountValue;
        
        log = new TransactionLog();
        initComponents();
    }
    
    
    private void generateReceipt(){
        FileHandling filehandler = new FileHandling();
        double amount = Double.parseDouble(issuedAmountValue);
        filehandler.saveReceipt(account.getAccountNumber(), operationTypeValue, amount);
    }
    
    public Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel64 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        errorMessage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        operationType = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        accountNumber = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        updatedBalance1 = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        issuedAmount = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        issuedDate = new Objects.RoundLabel("test", new Color(232, 199, 102), Color.white);
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        backToTransactionButton = new UI_Components.SubmitButton(null, "Back To Transaction Menu");
        ;
        jLabel58 = new javax.swing.JLabel();
        backToTransactionButton1 = new UI_Components.BackButton(null, "Log out");
        ;
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rceipt");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(231, 230, 221));
        jPanel1.setForeground(new java.awt.Color(231, 230, 221));
        jPanel1.setLayout(new java.awt.GridLayout(10, 5, 0, 25));
        jPanel1.add(jLabel60);
        jPanel1.add(jLabel7);
        jPanel1.add(jLabel61);
        jPanel1.add(jLabel62);
        jPanel1.add(jLabel9);
        jPanel1.add(jLabel65);
        jPanel1.add(jLabel63);

        errorMessage.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        errorMessage.setForeground(new java.awt.Color(232, 199, 102));
        errorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorMessage.setText("Operation Success");
        errorMessage.setText("");
        jPanel1.add(errorMessage);
        jPanel1.add(jLabel10);
        jPanel1.add(jLabel36);
        jPanel1.add(jLabel37);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Operation Type:");
        jPanel1.add(jLabel3);
        jPanel1.add(jLabel38);

        operationType.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        operationType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operationType.setText("19216191");
        operationType.setText(operationTypeValue);
        operationType.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                operationTypeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(operationType);
        jPanel1.add(jLabel39);
        jPanel1.add(jLabel40);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setText("Account Number:");
        jPanel1.add(jLabel2);
        jPanel1.add(jLabel41);

        accountNumber.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        accountNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accountNumber.setText("19216191");
        accountNumber.setText(account.getAccountNumber());
        accountNumber.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                accountNumberAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(accountNumber);
        jPanel1.add(jLabel42);
        jPanel1.add(jLabel43);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setText("Updated Balance:");
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel44);

        updatedBalance1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        updatedBalance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatedBalance1.setText("69420");

        updatedBalance1.setText("₱ " + String.valueOf(Math.floor(account.getAccountBalance() * 100) / 100));
        updatedBalance1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                updatedBalance1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(updatedBalance1);
        jPanel1.add(jLabel45);
        jPanel1.add(jLabel46);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setText("Isuued Amount:");
        jPanel1.add(jLabel6);
        jPanel1.add(jLabel47);

        issuedAmount.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        issuedAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issuedAmount.setText("6/08/2022");
        issuedAmount.setText("₱ "+ issuedAmountValue);
        issuedAmount.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                issuedAmountAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(issuedAmount);
        jPanel1.add(jLabel48);
        jPanel1.add(jLabel49);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel5.setText("Issued Date:");
        jPanel1.add(jLabel5);
        jPanel1.add(jLabel50);

        issuedDate.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        issuedDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issuedDate.setText("6/08/2022");

        issuedDate.setText(log.getDateTime());
        issuedDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                issuedDateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(issuedDate);
        jPanel1.add(jLabel51);
        jPanel1.add(jLabel52);
        jPanel1.add(jLabel53);
        jPanel1.add(jLabel54);
        jPanel1.add(jLabel55);
        jPanel1.add(jLabel56);
        jPanel1.add(jLabel57);

        backToTransactionButton.setBackground(new java.awt.Color(51, 97, 172));
        backToTransactionButton.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        backToTransactionButton.setForeground(java.awt.Color.white);
        backToTransactionButton.setText("Back To Transaction Menu");
        backToTransactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToTransactionButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backToTransactionButton);
        jPanel1.add(jLabel58);

        backToTransactionButton1.setBackground(new java.awt.Color(93, 93, 93));
        backToTransactionButton1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        backToTransactionButton1.setForeground(java.awt.Color.white);
        backToTransactionButton1.setText("Log out");
        backToTransactionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToTransactionButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backToTransactionButton1);
        jPanel1.add(jLabel59);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuedDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_issuedDateAncestorAdded

    }//GEN-LAST:event_issuedDateAncestorAdded

    private void accountNumberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_accountNumberAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberAncestorAdded

    private void updatedBalance1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_updatedBalance1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_updatedBalance1AncestorAdded

    private void backToTransactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToTransactionButtonActionPerformed
       generateReceipt();
       Transaction transaction = new Transaction(account);
       transaction.setVisible(true);
       transaction.setDefaultCloseOperation(EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_backToTransactionButtonActionPerformed

    private void backToTransactionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToTransactionButton1ActionPerformed
        Main_Menu menu = new Main_Menu();
        this.dispose();
    }//GEN-LAST:event_backToTransactionButton1ActionPerformed

    private void issuedAmountAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_issuedAmountAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_issuedAmountAncestorAdded

    private void operationTypeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_operationTypeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_operationTypeAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JButton backToTransactionButton;
    private javax.swing.JButton backToTransactionButton1;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel issuedAmount;
    private javax.swing.JLabel issuedDate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel operationType;
    private javax.swing.JLabel updatedBalance1;
    // End of variables declaration//GEN-END:variables
}
